version: "3.9"

services:
  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ~/redis-stack/local-data:/data
    restart: unless-stopped
    network_mode: bridge
